name: py3.7-torch0.4.1-cuda9.2
channels:
  - <unknown>
  - conda-forge
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - pytorch=0.4.1=py37_cuda9.2.148_cudnn7.1.4_1
  - certifi=2019.3.9=py37_0
  - mahotas=1.4.5=py37h637b7d7_1000
  - geos=3.7.1=he6710b0_0
  - mkl_fft=1.0.6=py37h7dd41cf_0
  - mkl_random=1.0.1=py37h4414c95_1
  - numpy=1.15.4=py37h1d66e8a_0
  - numpy-base=1.15.4=py37h81de0dd_0
  - pip=19.0.3=py37_0
  - python=3.7.1=h0371630_7
  - setuptools=40.8.0=py37_0
  - shapely=1.6.4=py37h86c5351_0
  - wheel=0.33.1=py37_0
  - blas=1.0=mkl
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2018.03.07=0
  - cairo=1.14.12=h8948797_3
  - cffi=1.11.5=py37he75722e_1
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.1.2=cuda9.0_0
  - cycler=0.10.0=py37_0
  - cython=0.29=py37he6710b0_0
  - dbus=1.13.2=h714fa37_1
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.12=h23475e2_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.0=118
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.0.1=py37hf484d3e_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.35=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - matplotlib=2.2.2=py37hb69df0a_2
  - mkl=2018.0.3=1
  - nccl=1.3.5=cuda9.0_0
  - ncurses=6.1=hf484d3e_0
  - ninja=1.8.2=py37h6bb024c_1
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1a=h7b6447c_0
  - pcre=8.42=h439df22_0
  - pillow=5.3.0=py37h34e0f95_0
  - pixman=0.34.0=hceecf20_3
  - py-opencv=3.4.2=py37hb342d67_1
  - pycparser=2.19=py37_0
  - pyparsing=2.3.0=py37_0
  - pyqt=5.6.0=py37h22d08a2_6
  - python-dateutil=2.7.5=py37_0
  - pytz=2018.7=py37_0
  - qt=5.6.3=h8bf5577_3
  - readline=7.0=h7b6447c_5
  - sip=4.18.1=py37hf484d3e_2
  - six=1.11.0=py37_1
  - sqlite=3.25.3=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py37h7b6447c_0
  - tqdm=4.28.1=py37h28b3542_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
  - torchvision=0.2.1=py37_1
  - pip:
    - absl-py==0.7.0
    - addict==2.2.0
    - astor==0.7.1
    - chardet==3.0.4
    - fake-useragent==0.1.11
    - future==0.17.1
    - gast==0.2.2
    - grpcio==1.18.0
    - gym==0.12.0
    - h5py==2.9.0
    - house3d==1.0.0
    - idna==2.7
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - lmdb==0.94
    - markdown==3.0.1
    - mmcv==0.2.1
    - mock==2.0.0
    - opencv-python==4.0.0.21
    - pandas==0.24.1
    - pbr==5.1.2
    - protobuf==3.6.1
    - pycocotools==2.0.0
    - pyglet==1.3.2
    - pyyaml==3.13
    - requests==2.20.1
    - scipy==1.2.1
    - selenium==3.141.0
    - tensorboard==1.13.0
    - tensorboardx==1.4
    - tensorflow-estimator==1.13.0
    - tensorflow-gpu==1.13.1
    - termcolor==1.1.0
    - terminaltables==3.1.0
    - torch==0.4.1
    - urllib3==1.24.1
    - warpctc-pytorch==0.1
    - werkzeug==0.14.1
prefix: /home/chenriquan/anaconda3/envs/py3.7-torch0.4.1-cuda9.2

